### ISSUE TITLE
Reject multiple int input 

### ISSUE THREAD

**Issue by evehill34** [evehill34/Sort#1]

**Comment by Serial-DeV** [comment]
Hello, I have an idea about how to solve this issue. Can I help you?

**Comment by evehill34** [comment]
OC, thanks

**Comment by Serial-DeV** [comment]
I'm done, just added a new regex pattern + regex search instead of regex match

**Comment by evehill34** [comment]
Nice perfect, I can close this issue

**Comment by evehill34** [comment]
Don't forget to follow me, I might have some other stuff I'm currently implementing (trying at least)

**Comment by Serial-DeV** [comment]
👍
